// src/app/components/user-management/user-management.component.ts
import { Component, OnInit } from '@angular/core';
import { UserService } from '../../services/user.service';
import { UserModel } from '../../Models/UserModel';

@Component({
  selector: 'app-user-management',
  templateUrl: './user-management.component.html',
  styleUrls: ['./user-management.component.css'],
})
export class UserManagementComponent implements OnInit {
  users: UserModel[] = [];
  originalUsersData: { [key: string]: UserModel } = {};

  constructor(private userService: UserService) {}

  ngOnInit(): void {
    this.userService.getAllUsers().subscribe((users) => {
      this.users = users;
      users.forEach((user) => {
        this.originalUsersData[user.userName] = { ...user };
      });
    });
  }

  anyChanges(): boolean {
    return this.users.some((user) => {
      const original = this.originalUsersData[user.userName];
      return JSON.stringify(original) !== JSON.stringify(user);
    });
  }

  updateUsers(): void {
    const usersToUpdate = this.users.filter((user) => {
      const original = this.originalUsersData[user.userName];
      return JSON.stringify(original) !== JSON.stringify(user);
    });

    if (usersToUpdate.length > 0) {
      this.userService.updateUser(usersToUpdate).subscribe({
        next: () => {
          console.log('Users updated successfully.');
          usersToUpdate.forEach((user) => {
            this.originalUsersData[user.userName] = { ...user };
          });
        },
        error: (error) => console.error('Failed to update users:', error),
      });
    } else {
      console.log('No changes to update.');
    }
  }
}

<div>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Gender</th>
        <th>Department</th>
        <th>Age</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let user of users">
        <td><input type="text" [(ngModel)]="user.name" /></td>
        <td><input type="text" [(ngModel)]="user.gender" /></td>
        <td><input type="text" [(ngModel)]="user.department" /></td>
        <td><input type="number" [(ngModel)]="user.age" /></td>
      </tr>
    </tbody>
  </table>
  <button [disabled]="!anyChanges()" (click)="updateUsers()">
    Update Users
  </button>
</div>

// practiceclinetreact/user-management-client/src/components/UserManagement.jsx
import React, { useState, useEffect } from "react";
import { getAllUsers, updateUser } from "../services/UserService";

function UserManagement() {
  const [users, setUsers] = useState([]);
  const [originalUsersData, setOriginalUsersData] = useState({});

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    const response = await getAllUsers();
    setUsers(response.data);
    const originalData = response.data.reduce((acc, user) => {
      acc[user.userName] = { ...user };
      return acc;
    }, {});
    setOriginalUsersData(originalData);
  };

  const handleInputChange = (userName, field, value) => {
    const updatedUsers = users.map((user) =>
      user.userName === userName ? { ...user, [field]: value } : user
    );
    setUsers(updatedUsers);
  };

  const anyChanges = () => {
    return users.some(
      (user) =>
        JSON.stringify(originalUsersData[user.userName]) !==
        JSON.stringify(user)
    );
  };

  const handleUpdateUsers = async () => {
    if (anyChanges()) {
      const updatedUsers = users.filter(
        (user) =>
          JSON.stringify(originalUsersData[user.userName]) !==
          JSON.stringify(user)
      );
      await updateUser(updatedUsers);
      fetchUsers(); // Re-fetch users to reset the original data
    }
  };

  return (
    <div>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Department</th>
            <th>Age</th>
          </tr>
        </thead>
        <tbody>
          {users.map((user) => (
            <tr key={user.userName}>
              <td>
                <input
                  type="text"
                  value={user.name}
                  onChange={(e) =>
                    handleInputChange(user.userName, "name", e.target.value)
                  }
                />
              </td>
              <td>
                <input
                  type="text"
                  value={user.gender}
                  onChange={(e) =>
                    handleInputChange(user.userName, "gender", e.target.value)
                  }
                />
              </td>
              <td>
                <input
                  type="text"
                  value={user.department}
                  onChange={(e) =>
                    handleInputChange(
                      user.userName,
                      "department",
                      e.target.value
                    )
                  }
                />
              </td>
              <td>
                <input
                  type="number"
                  value={user.age}
                  onChange={(e) =>
                    handleInputChange(user.userName, "age", e.target.value)
                  }
                />
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <button disabled={!anyChanges()} onClick={handleUpdateUsers}>
        Update Users
      </button>
    </div>
  );
}

export default UserManagement;
